# Generated by Django 2.0 on 2018-09-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.User')),
            ],
        ),
        migrations.CreateModel(
            name='PicVoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_ip', models.GenericIPAddressField()),
                ('type', models.IntegerField()),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.PictureEntry')),
            ],
        ),
    ]
