# Generated by Django 2.0 on 2018-09-04 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picvotelog',
            name='remote_ip',
        ),
        migrations.AddField(
            model_name='picvotelog',
            name='src',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pictureentry',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
